// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjumkx88hM35vdg02aV3ICqDwHgdAKrxs',
    appId: '1:906736201060:web:54d0e6faa8ba1ebb0b1e71',
    messagingSenderId: '906736201060',
    projectId: 'appli-ena',
    authDomain: 'appli-ena.firebaseapp.com',
    storageBucket: 'appli-ena.firebasestorage.app',
    measurementId: 'G-K3BXK9RL7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCexCkMxt60GpttjQdZSLXZDJhSC5JzwhQ',
    appId: '1:906736201060:android:bbedb319348fa58d0b1e71',
    messagingSenderId: '906736201060',
    projectId: 'appli-ena',
    storageBucket: 'appli-ena.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUJOBoaGySbrs7JVJi0rrTkktA7gGMDeo',
    appId: '1:906736201060:ios:9ec6e07c5524b8450b1e71',
    messagingSenderId: '906736201060',
    projectId: 'appli-ena',
    storageBucket: 'appli-ena.firebasestorage.app',
    iosBundleId: 'cd.ena.appliEna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUJOBoaGySbrs7JVJi0rrTkktA7gGMDeo',
    appId: '1:906736201060:ios:9ec6e07c5524b8450b1e71',
    messagingSenderId: '906736201060',
    projectId: 'appli-ena',
    storageBucket: 'appli-ena.firebasestorage.app',
    iosBundleId: 'cd.ena.appliEna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjumkx88hM35vdg02aV3ICqDwHgdAKrxs',
    appId: '1:906736201060:web:de4dbb426737fa240b1e71',
    messagingSenderId: '906736201060',
    projectId: 'appli-ena',
    authDomain: 'appli-ena.firebaseapp.com',
    storageBucket: 'appli-ena.firebasestorage.app',
    measurementId: 'G-66F8PVB16E',
  );
}
